const fs = require('fs');

let content = fs.readFileSync('src/app/dashboard/page.tsx', 'utf8');

content = content.replace(
  "<th style={{ padding: '16px', textAlign: 'left', fontWeight: 900, color: '#cca334' }}>KODE AKUN</th>\n                      <th style={{ padding: '16px', textAlign: 'left', fontWeight: 900, color: '#cca334' }}>NAMA AKUN</th>\n                      <th style={{ padding: '16px', textAlign: 'left', fontWeight: 900, color: '#cca334' }}>KATEGORI</th>\n                      <th style={{ padding: '16px', textAlign: 'left', fontWeight: 900, color: '#cca334' }}>SALDO NORMAL</th>\n                      <th style={{ padding: '16px', textAlign: 'right', fontWeight: 900, color: '#cca334' }}>AKSI</th>",
  "<th style={{ padding: '12px 16px', textAlign: 'left', fontWeight: 900, color: '#cca334' }}>KODE AKUN</th>\n                      <th style={{ padding: '12px 16px', textAlign: 'left', fontWeight: 900, color: '#cca334' }}>NAMA AKUN</th>\n                      <th style={{ padding: '12px 16px', textAlign: 'left', fontWeight: 900, color: '#cca334' }}>KATEGORI</th>\n                      <th style={{ padding: '12px 16px', textAlign: 'left', fontWeight: 900, color: '#cca334' }}>SALDO NORMAL</th>\n                      <th style={{ padding: '12px 16px', textAlign: 'right', fontWeight: 900, color: '#cca334' }}>AKSI</th>"
);

content = content.replace(
  "<td style={{ padding: '16px', fontSize: '15px', fontWeight: 800, fontFamily: 'monospace' }}>{coa.code}</td>\n                        <td style={{ padding: '16px', fontSize: '15px', fontWeight: 600 }}>{coa.name}</td>\n                        <td style={{ padding: '16px', fontSize: '14px' }}>\n                          <span style={{ background: 'rgba(255,255,255,0.1)', padding: '4px 10px', borderRadius: '6px' }}>{coa.category}</span>\n                        </td>\n                        <td style={{ padding: '16px', fontSize: '14px' }}>\n                          <span style={{ background: coa.normal_balance === 'Kredit' ? 'rgba(239,68,68,0.1)' : 'rgba(16,185,129,0.1)', color: coa.normal_balance === 'Kredit' ? '#ef4444' : '#10b981', padding: '4px 10px', borderRadius: '6px', fontWeight: 800 }}>{coa.normal_balance || 'Debit'}</span>\n                        </td>\n                        <td style={{ padding: '16px', textAlign: 'right' }}>\n                          <button onClick={() => {\n                            setEditingCoa(coa);\n                            setNewCoaCode(coa.code);\n                            setNewCoaName(coa.name);\n                            setNewCoaCategory(coa.category);\n                            setNewCoaNormalBalance(coa.normal_balance || 'Debit');\n                            setIsCoaModalOpen(true);\n                          }} style={{ background: 'transparent', border: '1px solid #cca334', color: '#cca334', padding: '6px 12px', borderRadius: '6px', cursor: 'pointer', marginRight: '8px' }}>Edit</button>\n                          <button onClick={() => handleDeleteCoa(coa.id, coa.code)} style={{ background: 'transparent', border: '1px solid #ef4444', color: '#ef4444', padding: '6px 12px', borderRadius: '6px', cursor: 'pointer' }}>Hapus</button>\n                        </td>",
  "<td style={{ padding: '8px 16px', fontSize: '14px', fontWeight: 800, fontFamily: 'monospace' }}>{coa.code}</td>\n                        <td style={{ padding: '8px 16px', fontSize: '14px', fontWeight: 600 }}>{coa.name}</td>\n                        <td style={{ padding: '8px 16px', fontSize: '13px' }}>\n                          <span style={{ background: 'rgba(255,255,255,0.1)', padding: '4px 8px', borderRadius: '6px' }}>{coa.category}</span>\n                        </td>\n                        <td style={{ padding: '8px 16px', fontSize: '13px' }}>\n                          <span style={{ background: coa.normal_balance === 'Kredit' ? 'rgba(239,68,68,0.1)' : 'rgba(16,185,129,0.1)', color: coa.normal_balance === 'Kredit' ? '#ef4444' : '#10b981', padding: '4px 8px', borderRadius: '6px', fontWeight: 800 }}>{coa.normal_balance || 'Debit'}</span>\n                        </td>\n                        <td style={{ padding: '8px 16px', textAlign: 'right' }}>\n                          <div style={{ display: 'flex', gap: '8px', justifyContent: 'flex-end', alignItems: 'center' }}>\n                            <button onClick={() => {\n                              setEditingCoa(coa);\n                              setNewCoaCode(coa.code);\n                              setNewCoaName(coa.name);\n                              setNewCoaCategory(coa.category);\n                              setNewCoaNormalBalance(coa.normal_balance || 'Debit');\n                              setIsCoaModalOpen(true);\n                            }} style={{ background: 'transparent', border: '1px solid #cca334', color: '#cca334', padding: '4px 10px', fontSize: '13px', borderRadius: '6px', cursor: 'pointer' }}>Edit</button>\n                            <button onClick={() => handleDeleteCoa(coa.id, coa.code)} style={{ background: 'transparent', border: '1px solid #ef4444', color: '#ef4444', padding: '4px 10px', fontSize: '13px', borderRadius: '6px', cursor: 'pointer' }}>Hapus</button>\n                          </div>\n                        </td>"
);

fs.writeFileSync('src/app/dashboard/page.tsx', content);
console.log('Table layout patched successfully');
