// __tests__/supabase_migration.test.ts
import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL as string;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY as string;
const supabase = createClient(supabaseUrl, supabaseKey);

// Load the table map generated by scan_supabase_tables.js
const tablesMapPath = path.resolve(__dirname, '..', 'supabase', 'tables_map.json');
const tablesMap = JSON.parse(fs.readFileSync(tablesMapPath, 'utf8')) as Record<string, string[]>;

describe('Supabase migrations verification', () => {
  // Verify that each referenced table exists in the database schema
  for (const table of Object.keys(tablesMap)) {
    test(`table ${table} exists`, async () => {
      const { data, error } = await supabase
        .from('information_schema.tables')
        .select('table_name')
        .eq('table_schema', 'public')
        .eq('table_name', table);
      expect(error).toBeNull();
      expect(data?.length).toBeGreaterThan(0);
    });
  }
});
